# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-06 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180704_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='theme',
            field=models.CharField(max_length=32, verbose_name='博客的个人主题样式'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=64, verbose_name='博客标题'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.FileField(default='/static/images/default_avatar.png', upload_to='avatars/'),
        ),
    ]
